from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, Field


class BaseAgent(ABC):
    """Abstract base class for extraction agents.

    All agents should implement the `run` method which executes the
    extraction workflow and returns structured results.
    """

    @abstractmethod
    def run(self, text: str, **kwargs) -> dict[str, Any]:
        """Execute the extraction workflow.

        Args:
            text: Input text to process
            **kwargs: Additional parameters specific to the agent

        Returns:
            Dictionary containing extraction results
        """
        pass


class ChunkerModel(BaseModel):
    chunker_cls: str = Field(
        ...,
        description="""Name of the chunker class used.""",
    )
    chunker_params: dict | None = Field(
        None,
        description="""Parameters used to initialize the chunker. This includes options like
        chunk size and overlap.""",
    )
    hash: str | None = Field(
        None,
        description="""Hash used as identifier to know if the chunking has to be run or
        skipped because it already exists.""",
    )
    chunks: list[str] | None = Field(
        None,
        description="""List of text chunks generated by the chunker.""",
    )
    run_time: float | None = Field(
        None,
        description="""Time taken to chunk the text in seconds.""",
    )


class RetrieverModel(BaseModel):
    retriever_cls: str = Field(
        ...,
        description="""Name of the retriever class used.""",
    )
    hash: str | None = Field(
        None,
        description="""Hash used as identifier to know if the retrieval has to be run or
        skipped because it already exists.""",
    )
    chunker_hash: str | None = Field(
        None,
        description="""Hash used as identifier to know which chunks the retriever is using
        as input.""",
    )
    model: str | None = Field(
        None,
        description="""Name of the model used in the retriever.""",
    )
    n_top_chunks: int | None = Field(
        None,
        description="""Number of top chunks retrieved by the retriever.""",
    )
    retriever_params: dict | None = Field(
        None,
        description="""Parameters used to initialize the retriever. This includes the
        retriever query and other options.""",
    )
    run_time: float | None = Field(
        None,
        description="""Time taken to retrieve the top chunks in seconds.""",
    )
    retrieved_text: str | None = Field(
        None,
        description="""Concatenated string of the top chunks retrieved by the retriever.""",
    )


class GeneratorModel(BaseModel):
    generator_cls: str = Field(
        ...,
        description="""Name of the generator class used.""",
    )
    chunker_hash: str | None = Field(
        None,
        description="""Hash used as identifier to know which chunks the generator used.""",
    )
    retriever_hash: str | None = Field(
        None,
        description="""Hash used as identifier to know which retrieved top chunks the
        generator used.""",
    )
    model: str | None = Field(
        None,
        description="""Name of the model used in the generator.""",
    )
    query: str | None = Field(
        None,
        description="""Query used by the generator as defined as keys in `PROMPTS_REGISTRY`.""",
    )
    llm_options: dict | None = Field(
        None,
        description="""Options used to initialize the LLM generator.""",
    )
    run_time: float | None = Field(
        None,
        description="""Time taken to generate the answer in seconds.""",
    )
    prompt: str | None = Field(
        None,
        description="""Full prompt sent to the LLM generator.""",
    )
    answer: str | None = Field(
        None,
        description="""Raw answer generated by the LLM.""",
    )


class RAGExtractorModel(BaseModel):
    start_time: str | None = Field(
        None,
        description="""Timestamp in ISO format when the RAG pipeline started.""",
    )
    end_time: str | None = Field(
        None,
        description="""Timestamp in ISO format when the RAG pipeline ended.""",
    )
