site_name: NERxiv
site_description: Documentation page for NERxiv.
site_author: Jose M. Pizarro
repo_url: https://github.com/JosePizarro3/NERxiv
nav:
  - Home: index.md
  - Tutorial:
    - Downloading arXiv papers as HDF5 files: tutorials/pyrxiv_download_hdf5.md
    - Using the RAG Extractor Agent: tutorials/rag_extractor_tutorial.md
  - How-to guides:
    - Customize Chunking Strategies: howtos/customize-chunking.md
    - Configure Retrieval Models: howtos/configure-retrieval-models.md
    - Use Different LLM Models: howtos/use-different-llm-models.md
    - Create Custom Prompts: howtos/create_custom_prompts.md
    - Adjust LLM Parameters: howtos/adjust-llm-parameters.md
  - Explanations:
    - What is RAG?: explanations/what-is-rag.md
    - Understanding Chunking Strategies: explanations/chunking-strategies.md
    - How Semantic Retrieval Works: explanations/semantic-retrieval.md
    - Prompt Engineering for Metadata Extraction: explanations/prompt-engineering.md
  - References:
    - API Reference: references/api.md
theme:
  name: material
  palette:
    primary: custom
    accent: custom
    # - scheme: default
    # - media: "(prefers-color-scheme: light)"
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to light mode
    # - scheme: slate
    # - media: "(prefers-color-scheme: dark)"
      # toggle:
      #   icon: material/weather-night
      #   name: Switch to dark mode
  logo: assets/nerxiv_logo.png
  favicon: assets/nerxiv_logo.png
  features:
    - navigation.path
    - navigation.footer
    - navigation.top
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: true  # show inheritance from classes
            show_source: true  # show source code
            show_if_no_docstring: true  # show methods if they don't have docstrings
            show_labels: false  # not showing labels in class attrs
            docstring_section_style: spacy  # different style for input parameters of methods
            members_order: source  # order of definitions according to source code
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js'
  - 'https://unpkg.com/cytoscape@3.19.1/dist/cytoscape.min.js'